version: 2
updates:
  # Enable version updates for Composer (PHP)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "mehmetmasa"
    labels:
      - "dependencies"
      - "php"
    commit-message:
      prefix: "🔒"
      include: "scope"

  # Enable version updates for npm (JavaScript)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "mehmetmasa"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "🔒"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "🔒"
      include: "scope"

